### ISSUE TITLE
SPARQL Queries are not being saved

### ISSUE THREAD

**Issue by retog** [edulod/lodide#12]
For example `https://raw.githubusercontent.com/retog/lodide-saved-contents/master/my-sparql-select-solution.ttl` contains no taskSolutionCodeCurrent and taskSolutionResourceCurrent in the dataSource section even if there was content in the respective fields at the time of saving.

**Comment by retog** [comment]
Curiously though, the show solution button is no longer available when working on the saved version.

**Comment by retog** [comment]
When accessing e.g. http://lodide.io/?exercise=https://raw.githubusercontent.com/retog/lodide-saved-contents/master/spex.ttl the query doesn't show up but only the endpoint. Also it wrongly shows "URI Pointing to RDF" , if I manually change this AND click into the query area, I see the query. The "show solution" button that was there when saving is also no longer there after saving and opening the saved version.

**Comment by alemela** [comment]
It wrongly shows "URI Pointing to RDF" because saved file are treated like exercises, in which you have always to manually change the source type. Others instead are bugs.

I think the solution could be adding another triple like ```<> lodide:sourceType lodide:SPARQL``` and iff it's present the intereface set automatically the source type. @retog what do you think?

**Comment by alemela** [comment]
Note for me: show button doesn't work because in saved file we don't store `lodide:taskSolutionType`.

**Comment by retog** [comment]
After saving a query and opening the saved query I see two issues:
- The query only appears when I click in the respective text area
- The query doesn't run, I get a dialog saying: "Error occurred with SPARQL query. Check the syntax of your query or the endpoint URL."

The query did run (resulting in XML rather than JSON but that's issue #19) before saving and reopening.

Here's a saved query: http://lodide.io/?exercise=https://raw.githubusercontent.com/retog/lodide-saved-contents/master/SPARQL.ttl

**Comment by alemela** [comment]
Fixed the bug related to this issue with: https://github.com/edulod/lodide/commit/49e206283d79c58b5fc2a81e4a8d58502ecbefc2
