### ISSUE TITLE
Show solution button not working for direct-input data sources

### ISSUE THREAD

**Issue by retog** [edulod/lodide#13]
e.g. in the "Verify a statement" exercise

**Comment by retog** [comment]
It works for the code and the data-rendering section

**Comment by retog** [comment]
Ok, it seems the code shows up when I click into the code section. So there's a missing refresh or so.

**Comment by alemela** [comment]
Yes, I had same issue with SPARQL code data section. The problem is about creating another "layer" without cleaning the standard one. I resolved with a ```$("#sparqlEditor").html("");``` and switching lines 167 and 168 of lodide.js
